### ISSUE TITLE
Strange text on Attribute:

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#35]
OUT-PATIENT_ATTENDANCE_INDICATOR_FOR_RADIOTHERAPY_DATA_SET: “then an Out-Patient Attendance recordis required, and National Code&#8216;Out-Patient Attendance recorded&#8217; applies.” National Codes:”

**Comment by maxChappell** [comment]
Looks like this is fixed?

**Comment by AngelaFaulding** [comment]
It doesn't match the current version exactly.
There is an extra bullet between the two "Where the PATIENT" and the final part "then an" is not indented.
Can this be fixed?

**Comment by maxChappell** [comment]
Extra (empty) bullets also spotted on https://modelcatalogue.cs.ox.ac.uk/datadictionary/supporting_information/supporting_information/accident_and_emergency_investigation_table.html

**Comment by AngelaFaulding** [comment]
Accident and Emergency Investigation Table will be retired in the October release.

**Comment by AngelaFaulding** [comment]
Text still not displaying correctly in the beta version, looking to see if the original text be updated to resolve this.

**Comment by AngelaFaulding** [comment]
Fixed in the October release.
