### ISSUE TITLE
Class Relationships not displaying correctly in the Orchestrator

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#531]
I have created a new Class PERSON STATED EYE COLOUR and added a relationship to CATEGORY VALUED PERSON OBSERVATION.

The relationships don't display correctly in the Orchestrator.

<img width="427" alt="image" src="https://github.com/user-attachments/assets/ccd19392-66fe-48b9-9dea-ad19803a570a">

![image](https://github.com/user-attachments/assets/3f7219a9-d4d8-4886-898b-aeb22fa827f2)

**Comment by KatePalmerLilley** [comment]
Also, the relationship isn't showing in the change paper.

CR8001 - National Hair Colour Data Set Version 1 - PERSON STATED HAIR COLOUR / CATEGORY VALUE PERSON OBSERVATION relationship created

![image](https://github.com/user-attachments/assets/0db08e80-90cc-43a2-ab32-12d91695f234)

**Comment by pjmonks** [comment]
Class relationships not having the correct descriptions are a known issue which we are fixing in:

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#64

There is a fix in place, it is currently being reviewed and tested internally before we deploy to the test environment.

**Comment by AngelaFaulding** [comment]
19/08/24 - System C are working on this.

**Comment by AngelaFaulding** [comment]
This has been fixed and is waiting for deployment

**Comment by pjmonks** [comment]
This issue has been fixed and deployed to TEST, TRAINING and LIVE. Please move this to the "Ready for NHS E Testing" state.

**Comment by pjmonks** [comment]
One note about what I have fixed on the class relationships. To fix the issue required fixing the ingest process. I have re-ingested all released and in-flight branches, so the correct class relationship descriptions should appear in these branches, e.g. "August 2024" and "CR1915".

However, I have not touched your work in progress branches CR8000 and CR8001 since you are still working on them, In these branches the class relationships may not look correct, but that is because the data inside them is not supporting the change. To verify, please look at a released/in-flight branch to confirm.

**Comment by AngelaFaulding** [comment]
@pjmonks - please see #507.

Relationships for CATEGORY VALUED PERSON OBSERVATION - it is not only the new one that is not displaying correctly. A number that should have or do not, see https://www.datadictionary.nhs.uk/classes/category_valued_person_observation.html

![image](https://github.com/user-attachments/assets/0c15b02c-2954-4f4b-a4bf-86a4e0bb62a0)

Also, there are no relationships showing in either type of Changes preview:

![image](https://github.com/user-attachments/assets/1aca452b-1e3a-422c-8937-423e260bf9da)

![image](https://github.com/user-attachments/assets/740c923f-75a4-4b98-87a7-c6fd889b6560)

**Comment by pjmonks** [comment]
See this comment: https://github.com/NHSDigital/DataDictionaryPublication/issues/507#issuecomment-2368670679

**Comment by AngelaFaulding** [comment]
@pjmonks - the relationships are still not showing in Changes. These are not just for choice relationships.

In Mauro CR8008 shows relationships for PERSON STATED EYE COLOUR:

![image](https://github.com/user-attachments/assets/4032f82d-36d4-4bba-b6fa-7a2931f5d05a)

But there none in either version of Changes:

![image](https://github.com/user-attachments/assets/ca6e73cb-0652-4226-8e81-ea71ffe03d14)

**Comment by pjmonks** [comment]
@AngelaFaulding - also @stevebowring and @NellySSJ:

I was not aware that change papers are meant to include class relationships. The only samples of change papers taken from Borland Together do not include them, these are the ones you have provided me:

[ChangePaperSamples.zip](https://github.com/user-attachments/files/17113721/ChangePaperSamples.zip)

@stevebowring - has a requirement been missed here?

**Comment by AngelaFaulding** [comment]
Change Papers have always included Class relationships. Obviously not all Change Papers include changes to Classes. These were a sample of branches that were work in progress at the start of the project.

We can't move forward without this, see below for an example of changes in a Change Paper:

![image](https://github.com/user-attachments/assets/5299492f-8e28-4fda-a460-5371973c0f6c)

**Comment by AngelaFaulding** [comment]
Attached is an example of a CR with a changed relationship.
[0011372022ddcr1872-v2 (1).pdf](https://github.com/user-attachments/files/17113811/0011372022ddcr1872-v2.1.pdf)

**Comment by pjmonks** [comment]
@AngelaFaulding, @stevebowring, @NellySSJ - I will add the class relationship table/differences to the change papers. However, I will reiterate that this was not explained to us as a requirement before now.

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#136

**Comment by AngelaFaulding** [comment]
@pjmonks - I agree that the SOW was not explicit.
It said "Generate Change Requests (CRs) (basic and data set).  -	All content for CR will reside in Mauro. Capability to generate CR for a branch in Orchestrator, and also generate required output. Output will be a standard file format that will be accessed by NHSE for further processing to a readable form using style sheets that reside in GitHub."

As it refers to all content in Mauro we just expected that all content would be present in the CRs.

**Comment by AngelaFaulding** [comment]
30/09/24 - Peter is working on this, it needs to be deployed and tested.

**Comment by pjmonks** [comment]
I have deployed to TEST some additions to the Change Papers (plus preview), where Classes now list their relationships. I've also changed the formatting of the attributes/relationships into tables.

There are more fixes pending for the Change Papers to get the correct content present (see #525), for now this is what is available to test.

**Comment by KatePalmerLilley** [comment]
16/10/24 - this has been assessed.
